### ISSUE TITLE
Update for mongo 2.0

### ISSUE THREAD

**Issue by gkellogg** [ruby-rdf/rdf-mongo#3]
Mongo 2.0+ has some incompatible changes. It would probably be good to continue support for mongo 1.x until 2.0 is widely deployed. rdf-raptor does something similar for different raptor versions.

**Comment by abargnesi** [comment]
MongoDB has [documentation](https://docs.mongodb.org/ecosystem/drivers/ruby/) on Ruby Driver and reasons for new major release.

**Comment by gkellogg** [comment]
Mongo 2+ is supported in rdf-mongo 2.0.0.
